# Generated by Django 5.2.2 on 2026-02-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauditlog',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='userauditlog',
            name='previous_status',
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('Self Registered', 'Self Registered'), ('MODIFIED', 'Modified'), ('Disabled', 'Disabled')], max_length=20),
        ),
    ]
