# Generated by Django 5.2.2 on 2026-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='feeAssignment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='feeAssignment',
            field=models.ManyToManyField(related_name='feeAssignments', to='api.feeassignment'),
        ),
    ]
