# Generated by Django 5.2.2 on 2026-04-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionchangerequest',
            name='prev_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trx_prev', to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionchangerequest',
            name='trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trx', to='api.transaction'),
        ),
    ]
