# Generated by Django 5.2.2 on 2026-03-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ediruser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='edir',
            name='created_by',
        ),
        migrations.AddField(
            model_name='edirauditlog',
            name='new_status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edirauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ediruserauditlog',
            name='new_status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ediruserauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='new_status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='edirauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edirfamilyauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ediruser',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Blocked', 'Blocked'), ('Active', 'Active'), ('Not Active', 'Not Active'), ('Leaved', 'Leaved')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EdirChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DISABLE', 'Disable')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edir_checker', to=settings.AUTH_USER_MODEL)),
                ('edir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edir')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edir_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EdirUserChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('JOIN_REQUEST', 'Join Request'), ('LEAVE_REQUEST', 'Leave Request'), ('ADD_MEMBER', 'Add Member by Admin'), ('BLOCK_MEMBER', 'Block Member')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edir_user_checker', to=settings.AUTH_USER_MODEL)),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edir')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edir_user_maker', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ediruser',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='ediruser',
            name='maker',
        ),
    ]
