# Generated by Django 5.2.2 on 2025-12-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ediruser',
            table='customuser_edirs',
        ),
    ]
