# Generated by Django 5.2.2 on 2026-03-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transaction_feeassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='feeAssignment',
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx', to='api.transaction'),
        ),
    ]
