# Generated by Django 5.2.2 on 2026-03-07 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ediruser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ediruser',
            unique_together={('user', 'edir')},
        ),
        migrations.AlterField(
            model_name='edir',
            name='users',
            field=models.ManyToManyField(related_name='user_edir', through='api.EdirUser', through_fields=('edir', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ediruser',
            name='reason',
        ),
    ]
