# Generated by Django 5.2.2 on 2026-04-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feeassignment_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='approved_at',
            new_name='updated_at',
        ),
    ]
