# Generated by Django 5.2.2 on 2026-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userauditlog_new_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediruserauditlog',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='ediruserauditlog',
            name='previous_status',
        ),
        migrations.AlterField(
            model_name='ediruserauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('Disabled', 'Disabled'), ('BLOCKED', 'Blocked'), ('Leaved', 'Leaved'), ('Joined', 'Joined'), ('Requested to Join', 'Requested to Join'), ('Cancelled Join Request', 'Cancelled Join Request'), ('Added by Admin', 'Added by Admin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED by Admin', 'Created by Admin'), ('Self Registered', 'Self Registered'), ('MODIFIED', 'Modified'), ('Disabled', 'Disabled')], max_length=20),
        ),
    ]
