# Generated by Django 5.2.2 on 2026-04-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactionchangerequest_prev_trx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trx_user', to='api.ediruser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionchangerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trxreq_user', to='api.ediruser'),
        ),
    ]
