# Generated by Django 5.2.2 on 2026-02-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ediruserauditlog_new_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edirauditlog',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='edirauditlog',
            name='previous_status',
        ),
        migrations.AddField(
            model_name='edir',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ediruserauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('Disabled', 'Disabled'), ('BLOCKED', 'Blocked'), ('Leaved', 'Leaved'), ('Joined', 'Joined'), ('Requested to Join', 'Requested to Join'), ('Cancelled Join Request', 'Cancelled Join Request'), ('Added by Admin', 'Added by Admin'), ('Added when Create Edir', 'Added when Create Edir')], max_length=30),
        ),
    ]
