# Generated by Django 5.2.2 on 2026-04-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_user_alter_transactionchangerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_user', to='api.ediruser'),
        ),
        migrations.AlterField(
            model_name='transactionchangerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trxrequest_user', to='api.ediruser'),
        ),
    ]
