# Generated by Django 5.2.2 on 2025-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_country_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediruser',
            name='is_committee',
            field=models.BooleanField(default=True),
        ),
    ]
