# Generated by Django 5.2.2 on 2026-03-01 17:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_transaction_feeassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=api.models.generate_reference, editable=False, max_length=16, unique=True),
        ),
    ]
