# Generated by Django 5.2.2 on 2026-03-07 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ediruser_unique_together_alter_edir_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediruserauditlog',
            name='edirUser',
        ),
        migrations.AddField(
            model_name='edirchangerequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ediruserauditlog',
            name='edir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edirUserLogs', to='api.edir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ediruserauditlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edirUserLogs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edirchangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CREATED', 'Created')], default='PENDING', max_length=10),
        ),
    ]
