# Generated by Django 5.2.2 on 2025-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ediruser_is_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ediruser',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
    ]
