# Generated by Django 5.2.2 on 2026-03-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ediruserauditlog_ediruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ediruserchangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CREATED', 'Created')], default='PENDING', max_length=10),
        ),
    ]
