# Generated by Django 5.2.2 on 2026-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trxauditlog',
            name='new_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trxauditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
