# Generated by Django 5.2.2 on 2026-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_edirauditlog_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edir',
            name='monthly_fee',
            field=models.FloatField(),
        ),
    ]
