# Generated by Django 5.2.2 on 2026-04-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('PAYMENT', 'Payment')], max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('payment_status', models.CharField(choices=[('REVERSED', 'Reversed'), ('Cancelled', 'Cancelled'), ('Modified', 'Modified'), ('Paid', 'Paid')], default='Paid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='api.bank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_user', to='api.ediruser')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='api.deposit'),
        ),
    ]
