# Generated by Django 5.2.2 on 2026-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trxauditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxauditlog',
            name='action',
            field=models.CharField(choices=[('TRX_CREATED', 'Trx_Created'), ('TRX_APPROVED', 'Trx_Approved'), ('TRX_REJECTED', 'Trx_Rejected'), ('TRX_CANCELLED', 'Trx_Cancelled')], max_length=50),
        ),
    ]
