# Generated by Django 5.2.2 on 2025-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ediruser_is_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
