# Generated by Django 5.2.2 on 2026-03-10 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ediruserchangerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='maker',
        ),
        migrations.AlterField(
            model_name='bankauditlog',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankLogs', to='api.bank'),
        ),
        migrations.CreateModel(
            name='BankChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DISABLE', 'Disable')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CREATED', 'Created')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bank')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_checker', to=settings.AUTH_USER_MODEL)),
                ('edir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edir')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
