# Generated by Django 5.2.2 on 2026-03-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bank_checker_remove_bank_maker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='maker',
        ),
        migrations.CreateModel(
            name='ExpenseChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DISABLE', 'Disable')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_checker', to=settings.AUTH_USER_MODEL)),
                ('edir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edir')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fee')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
