# Generated by Django 5.2.2 on 2025-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_edir_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='meeting_place',
            field=models.CharField(blank=True, null=True),
        ),
    ]
