# Generated by Django 5.2.2 on 2026-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transaction_bank_remove_transaction_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
    ]
