# Generated by Django 5.2.2 on 2026-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
