# Generated by Django 5.2.2 on 2025-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_edir_meeting_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
                ('answer', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
