# Generated by Django 5.2.2 on 2026-03-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_fee_checker_remove_fee_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeauditlog',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeLogs', to='api.fee'),
        ),
    ]
