# Generated by Django 5.2.2 on 2026-05-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_deposit_payment_status_bank_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DISABLE', 'Disable')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_checker', to='api.ediruser')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit')),
                ('edir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edir')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_maker', to='api.ediruser')),
            ],
        ),
    ]
