# Generated by Django 5.2.2 on 2025-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='help',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
