# Generated by Django 5.2.2 on 2025-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_help_answer_alter_help_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='type',
            field=models.CharField(choices=[('Common', 'Common'), ('FAQ', 'FAQ')], default='FAQ', max_length=50),
        ),
    ]
