# Generated by Django 5.2.2 on 2026-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fee_amount_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
