# Generated by Django 5.2.2 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fee_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeassignment',
            name='maker',
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Active', max_length=30),
        ),
    ]
