# Generated by Django 5.2.2 on 2026-05-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_incomechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeassignment',
            name='transaction_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transactionchangerequest'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Fee', 'Fee')], default='Fee', max_length=20),
        ),
    ]
