# Generated by Django 5.2.2 on 2025-12-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_location_alter_event_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='edir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.edir'),
        ),
    ]
