# Generated by Django 5.2.2 on 2026-03-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_feeassignment_maker_alter_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeassignment',
            name='status',
            field=models.CharField(choices=[('Disabled', 'Disabled'), ('Active', 'Active')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='transaction_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_assignments_trx_request', to='api.transactionchangerequest'),
        ),
        migrations.AlterField(
            model_name='feeassignment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeassignment_trx', to='api.transaction'),
        ),
    ]
