# Generated by Django 5.2.2 on 2025-12-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_edir'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edir',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ediruser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
    ]
