# Generated by Django 5.2.2 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_feechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediruser',
            name='leave_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
