# Generated by Django 5.2.2 on 2025-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_edir_is_popular_edir_status_alter_ediruser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediruser',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ediruser',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ediruser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
    ]
