# Generated by Django 5.2.2 on 2025-12-26 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ediruser_updated_date_alter_ediruser_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
