# Generated by Django 5.2.2 on 2026-01-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
